Update build.yml
Signed-off-by: Sofiya <107557749+sofijacom@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,84 +1,176 @@
 name: "🏗️ Build Latest Packages"
  
+env:
+  TAG: workflow-${{ github.run_number }}
+  SHA: ${{ github.sha }}
+
 on:
   push:
-    branches: [ main ]
+    branches: [main]
+    paths: [srcpkgs/**]
   workflow_dispatch:
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
   build:
+    name: Build📦 ${{ matrix.config.arch }}
     runs-on: ubuntu-latest
+    permissions:
+      contents: write   
+    strategy:
+      fail-fast: false
+      matrix:
+        config:
+          - { arch: x86_64,       host: x86_64,      libc: glibc, platform: linux/amd64, test: 1 }
+          - { arch: i686,         host: i686,        libc: glibc, platform: linux/386,   test: 1 }
+          - { arch: aarch64,      host: x86_64,      libc: glibc, platform: linux/amd64, test: 0 }
+          - { arch: x86_64-musl,  host: x86_64-musl, libc: musl,  platform: linux/amd64, test: 1 }
+          - { arch: aarch64-musl, host: x86_64-musl, libc: musl,  platform: linux/amd64, test: 0 }
+          
     container:
-      image: ghcr.io/void-linux/void-glibc-full:20250227R1
-      options: --platform linux/amd64 --privileged
-
-    env:
-      TARGET_ARCH: x86_64
+      image: ghcr.io/void-linux/void-${{ matrix.config.libc }}-full:20250616R1
+      options: --platform ${{ matrix.config.platform }} --privileged
+      volumes:
+        - /dev:/dev
+      env:
+        TAG: '${{ env.TAG }}'
+        SHA: '${{ env.SHA }}'
+        ARCH: '${{ matrix.config.arch }}'
+        XBPS_TARGET_ARCH: '${{ matrix.config.arch }}'
+        REPO_OWNER: "${{ github.repository_owner }}"
+        REPO_NAME: "${{ github.event.repository.name }}"
+    if: ${{ github.ref == 'refs/heads/main' }}
 
     steps:
-      - name: 🔧 Подготовка
+      - name: Cache masterdir
+        uses: actions/cache@v5
+        with:
+          path: void-packages/masterdir-${{ matrix.config.arch }}
+          key: masterdir-${{ matrix.config.arch }}-${{ hashFiles('void-packages/common/xbps-src/shlibs') }}
+          restore-keys: |
+            masterdir-${{ matrix.config.arch }}-
+         
+      - name: Prep container
         run: |
           mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
-          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
-          xbps-install -Syu xbps && xbps-install -yu
-          xbps-install -y sudo git bash coreutils
-          useradd -m -G xbuilder builder -s /bin/bash
-          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
-
-      - name: 🌐 Клонируем void-packages
-        run: |
-          git clone --depth=1 https://github.com/void-linux/void-packages.git /home/builder/void-packages
-          chown -R builder:xbuilder /home/builder/void-packages
-
-
-      - name: 📦 binary-bootstrap
-        run: |
-          cd /home/builder/void-packages
-          sudo -Eu builder \
-          XBPS_NO_UNSHARE=1 \
-          ./xbps-src -a x86_64 -A x86_64 binary-bootstrap
-          # ВСЁ, ЧТО БЫЛО ПОСЛЕ — ЗАКОММЕНТИРОВАНО
-          # - name: 🚀 Сборка...
-          #   run: |
-          #     ./xbps-src ...   ← ❌ вот он, враг
-
-      - name: 🧪 Добавляем hello
-        run: |
-          cd /home/builder/void-packages
-          mkdir -p srcpkgs/hello
-          cat > srcpkgs/hello/template << 'EOF'
-          pkgname=hello
-          version=2.12
-          revision=1
-          build_style=gnu-configure
-          short_desc="GNU Hello, the classic hello world program"
-          maintainer="voidlinux@voidlinux.org"
-          license="GPL-3.0-or-later"
-          homepage="https://www.gnu.org/software/hello/"
-          distfiles="https://ftp.gnu.org/gnu/hello/hello-${version}.tar.gz"
-          checksum=64c9d4174ee312653359837626c7701a400959c9429195912e70f883168996f7
-          EOF
-          chown -R builder:xbuilder srcpkgs/hello
-
-      - name: 🚀 Сборка ВНУТРИ chroot
-        run: |
-          cd /home/builder/void-packages
-          MASTERDIR="masterdir-${TARGET_ARCH}"
-
-          chroot "$MASTERDIR" /bin/sh -c "
-            export XBPS_ALLOW_CHROOT_BREAKOUT=1
-            cd /void-packages
-            su - builder -c '
-              ./xbps-src -a x86_64 pkg hello
-            '
-          "
-
-      - name: 🗃️ Проверяем результат
-        run: |
-          find /home/builder/void-packages/hostdir/binpkgs -name "*.xbps" -ls
-
-      - name: 📦 Артефакт
-        uses: actions/upload-artifact@v4
+          env -u XBPS_TARGET_ARCH xbps-install -Syu xbps
+          env -u XBPS_TARGET_ARCH xbps-install -yu
+          env -u XBPS_TARGET_ARCH xbps-install -y sudo bash curl grep jq zip unzip git github-cli xtools coreutils
+          useradd -G xbuilder -M builder -s $(which bash)
+          
+      - name: 🔎 Checkout void-packages
+        uses: actions/checkout@v6
         with:
-          name: binpkgs
-          path: /home/builder/void-packages/hostdir/binpkgs/**/*.xbps
+          repository: void-linux/void-packages
+          ref: master
+          path: void-packages
+           
+      - name: 🧩 Merge this repository into void-linux/void-packages
+        working-directory: void-packages
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git config --global --add safe.directory "*"
+          git remote add -f xlibre-void https://github.com/xlibre-void/xlibre.git
+          git merge --no-commit --strategy-option=theirs --allow-unrelated-histories -Xignore-space-change xlibre-void/main
+          mkdir -p hostdir/binpkgs
+          
+          gh release download --pattern "*${ARCH}*" --dir hostdir/binpkgs --repo xlibre-void/xlibre || true
+          
+      - name: 📋 Identify changes to build
+        working-directory: void-packages
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          latest_name=$(gh release view --json tagName --jq '.tagName' --repo xlibre-void/xlibre || echo "Initial Commit")
+          latest_sha=$(git rev-list --max-count=1 ${latest_name} 2>/dev/null || git rev-list --max-parents=0 xlibre-void/main)
+          echo "Latest Tag Name: ${latest_name}"
+          echo "Latest Tag SHA: ${latest_sha}"
+
+          chown -R builder:builder .
+          git diff-tree -r --no-renames --name-only --diff-filter=AM ${latest_sha} ${SHA} -- 'srcpkgs/**' \
+          | cut -d/ -f 2 | uniq | xargs sudo -Eu builder ./xbps-src sort-dependencies | tee /tmp/templates
+
+      - name: 📋 Setup void-packages
+        working-directory: void-packages
+        run: |
+          chown -R builder:builder .
+          mkdir -p etc
+          echo XBPS_BUILD_ENVIRONMENT=void-packages-ci >> etc/conf
+          echo XBPS_ALLOW_RESTRICTED=yes >> etc/conf
+          echo XBPS_CHROOT_CMD=uchroot >> etc/conf
+          echo 'XBPS_REPOSITORY=$PWD/hostdir/binpkgs' >> etc/conf
+          echo 'XBPS_DISTDIR=$PWD/hostdir/distfiles' >> etc/conf
+          echo 'XBPS_MASTERDIR_PKGS="$PWD/hostdir/binpkgs"' >> etc/conf
+
+      - name: ✅ Prepare masterdir
+        working-directory: void-packages
+        run: |
+          chown -R builder:builder .
+          yes | sudo -Eu builder ./xbps-src -m masterdir-${{ matrix.config.arch }} -A ${{ matrix.config.arch }} binary-bootstrap
+
+      - name: 📦 build pkgs
+        working-directory: void-packages
+        run: |
+          chown -R builder:builder .
+          pkgs=$(cat /tmp/templates)
+          for pkg in ${pkgs}; do
+            echo "🏗️ Building $pkg for $ARCH..."
+            sudo -Eu builder ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.config.arch }} -A ${{ matrix.config.arch }} "${pkg}" || printf "Failed building ${pkg}!\n"
+          done
+
+      - name: 🧾 Clean & sign
+        working-directory: void-packages/hostdir/binpkgs
+        env:
+          PRIVKEY: ${{ secrets.PRIV_KEY }}
+          XBPS_PASSPHRASE: ${{ secrets.SIGN_PASS }}
+        run: |
+          sudo -Eu builder xbps-rindex --remove-obsoletes ${PWD}
+          printf "%s\n" "${PRIVKEY}" > key.pem
+          sudo -Eu builder xbps-rindex --privkey key.pem --sign --signedby "${REPO_NAME}-github-actions" --verbose ${PWD}
+          sudo -Eu builder xbps-rindex --privkey key.pem --sign-pkg --verbose ${PWD}/*.xbps
+          sudo -Eu builder rm -f key.pem
+          sudo -Eu builder xbps-rindex --clean ${PWD}
+
+      - name: 🔢 checksum
+        working-directory: void-packages/hostdir/binpkgs
+        run: |
+          rm -rf *.sha256sum *.sha512sum
+          
+          # Only run the loop if there are actually files ending in .xbps
+          count=$(ls -1 *.xbps 2>/dev/null | wc -l)
+          if [ "$count" != 0 ]; then
+            for file in *.xbps; do
+              sha256sum "${file}" | cut -d ' ' -f 1 > "${file}.sha256sum"
+              sha512sum "${file}" | cut -d ' ' -f 1 > "${file}.sha512sum"
+            done
+          else
+            echo "❌ No packages found to checksum."
+          fi
+
+      - name: 📤 Upload Artifact
+        uses: actions/upload-artifact@v7
+        with:
+          name: ${{ matrix.config.arch }}-repodata
+          path: void-packages/hostdir/binpkgs
+
+      - name: 🏷️ short sha
+        run: |
+          printf "SHORT_SHA=$(git rev-parse --short ${SHA})" >> $GITHUB_ENV
+
+      - name: 🚀 release
+        uses: softprops/action-gh-release@v3
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          name: ${{ env.SHORT_SHA }}
+          tag_name: ${{ env.TAG }}
+          files: |
+            void-packages/hostdir/binpkgs/*.xbps
+            void-packages/hostdir/binpkgs/*.sig2
+            void-packages/hostdir/binpkgs/*repodata
